# Generated by Django 4.1 on 2024-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('peticion', models.TextField(max_length=500)),
            ],
        ),
    ]
