# Generated by Django 4.2.30 on 2026-05-07 17:20

from django.db import migrations, models


def crear_sobre_mi_inicial(apps, schema_editor):
    SobreMiContenido = apps.get_model('base', 'SobreMiContenido')
    if SobreMiContenido.objects.exists():
        return
    SobreMiContenido.objects.create(
        titulo='¿Quién Soy?',
        texto=(
            'Mi identidad se teje entre las aulas de la Universidad de Sevilla, donde me sumerjo en el apasionante mundo '
            'de la Educación Primaria. En los momentos de pausa encuentro un refugio creativo en el diseño. '
            'La creatividad fluye cuando mis manos dan forma a ideas, ya sea a través del dibujo, la pintura o la creación digital. '
            'Cada prenda nace de una historia, una ocasión y una persona concreta.'
        ),
        instagram_url='https://www.instagram.com/lujapon_/',
        tiktok_url='https://www.tiktok.com/@lujapon_',
        twitter_url='https://twitter.com/',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_peticion_estado_peticion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMiContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='¿Quién Soy?', max_length=80)),
                ('texto', models.TextField(max_length=2500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sobre-mi/')),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido Sobre mí',
                'verbose_name_plural': 'Contenido Sobre mí',
            },
        ),
        migrations.AddField(
            model_name='peticion',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peticion',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='peticion',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='peticion',
            name='talla_aproximada',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='peticion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='peticion',
            name='tipo_prenda',
            field=models.CharField(choices=[('vestido', 'Vestido'), ('traje', 'Traje'), ('camiseta', 'Camiseta'), ('conjunto', 'Conjunto'), ('otro', 'Otro')], default='vestido', max_length=30),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='asunto',
            field=models.TextField(max_length=60),
        ),
        migrations.RunPython(crear_sobre_mi_inicial, migrations.RunPython.noop),
    ]
