# Generated by Django 4.1 on 2024-03-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='imagen_principal',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_principal_de', to='diseños.imagen'),
        ),
    ]
