# Generated by Django 4.1 on 2024-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0003_rename_description_diseño_descripccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='descripccion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='imagenes_adicionales',
            field=models.ManyToManyField(blank=True, related_name='imagenes_adicionales_de', to='diseños.imagen'),
        ),
    ]
