# Generated by Django 4.2.30 on 2026-05-07 17:03

from decimal import Decimal

from django.db import migrations, models


def asignar_precio_inicial(apps, schema_editor):
    Diseño = apps.get_model('diseños', 'Diseño')
    Diseño.objects.filter(precio=0).update(precio=Decimal('49.99'))


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0011_pedido_lineapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=49.99, max_digits=8),
        ),
        migrations.RunPython(asignar_precio_inicial, migrations.RunPython.noop),
    ]
