# Generated by Django 4.2.30 on 2026-05-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0012_alter_diseño_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
    ]
