# Generated by Django 4.2.30 on 2026-05-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseños', '0015_pedido_access_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disenolike',
            options={'ordering': ['-creado'], 'verbose_name': 'favorito', 'verbose_name_plural': 'favoritos'},
        ),
        migrations.AlterModelOptions(
            name='diseño',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'diseño', 'verbose_name_plural': 'diseños'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'imágenes'},
        ),
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'verbose_name': 'línea de pedido', 'verbose_name_plural': 'líneas de pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='disenolike',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='disenolike',
            name='diseño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='diseños.diseño', verbose_name='diseño'),
        ),
        migrations.AlterField(
            model_name='disenolike',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_disenos', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='categoria',
            field=models.CharField(choices=[('prenda', 'Prenda'), ('vestido', 'Vestido'), ('traje', 'Traje'), ('camiseta', 'Camiseta'), ('a_medida', 'A medida')], default='prenda', max_length=30, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='descripccion',
            field=models.CharField(blank=True, max_length=120, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de subida'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagen principal'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='imagenes_adicionales',
            field=models.ManyToManyField(blank=True, related_name='imagenes_adicionales_de', to='diseños.imagen', verbose_name='imágenes adicionales'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='popularidad',
            field=models.IntegerField(default=0, verbose_name='popularidad'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=49.99, max_digits=8, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='talla',
            field=models.CharField(blank=True, max_length=30, verbose_name='talla'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='diseño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseño_imagenes', to='diseños.diseño', verbose_name='diseño'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='images/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='diseño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_pedido', to='diseños.diseño', verbose_name='diseño'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='nombre_producto',
            field=models.CharField(max_length=80, verbose_name='nombre del producto'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='diseños.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio unitario'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='talla',
            field=models.CharField(blank=True, max_length=30, verbose_name='talla'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token de acceso'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(max_length=80, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(max_length=12, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('incidencia', 'Incidencia')], default='pendiente_pago', max_length=20, verbose_name='estado del pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='estado del pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(max_length=100, verbose_name='nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, max_length=500, verbose_name='notas del pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de sesión de Stripe'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID de pago de Stripe'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='usuario registrado'),
        ),
    ]
