# Generated by Django 4.2.30 on 2026-05-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0016_alter_disenolike_options_alter_diseño_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=30, verbose_name='talla')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_talla', to='diseños.diseño', verbose_name='diseño')),
            ],
            options={
                'verbose_name': 'stock por talla',
                'verbose_name_plural': 'stock por talla',
                'ordering': ['talla'],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktalla',
            constraint=models.UniqueConstraint(fields=('diseño', 'talla'), name='stock_unico_por_diseno_talla'),
        ),
    ]
