# Generated by Django 4.2.30 on 2026-05-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'verbose_name': 'perfil de cliente', 'verbose_name_plural': 'perfiles de cliente'},
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=80, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=12, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
