# Generated by Django 4.2.30 on 2026-05-07 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='peticion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peticiones', to=settings.AUTH_USER_MODEL),
        ),
    ]
