# Generated by Django 4.2.30 on 2026-05-07 20:30

from django.db import migrations, models
import django.utils.timezone


def crear_entradas_iniciales(apps, schema_editor):
    EntradaBlog = apps.get_model('base', 'EntradaBlog')
    if EntradaBlog.objects.exists():
        return
    EntradaBlog.objects.create(
        titulo='Cómo empezar un diseño a medida',
        slug='como-empezar-un-diseno-a-medida',
        entradilla='Una guía breve para preparar referencias, medidas e ideas antes de pedir una prenda personalizada.',
        contenido=(
            'Un diseño a medida empieza mucho antes de elegir la tela. Conviene pensar en la ocasión, el movimiento que necesitas, '
            'los colores que te favorecen y las prendas con las que te sientes cómoda.\n\n'
            'Si tienes referencias, fotos o dibujos, tráelos contigo. No tienen que ser perfectos: sirven para entender proporciones, '
            'escote, volumen, largo y detalles. También ayuda indicar una fecha límite y un presupuesto aproximado.'
        ),
        publicado=True,
    )
    EntradaBlog.objects.create(
        titulo='Ideas para elegir la talla y el ajuste',
        slug='ideas-para-elegir-la-talla-y-el-ajuste',
        entradilla='Consejos sencillos para explicar cómo quieres que siente una prenda: suelta, entallada o con volumen.',
        contenido=(
            'La talla es solo el principio. En una prenda especial importa mucho cómo quieres sentirla: cómoda, estructurada, ligera, '
            'marcada en cintura o con caída.\n\n'
            'Cuando rellenes una solicitud a medida, incluye tu talla habitual y cualquier detalle práctico: altura, largo preferido, '
            'si llevarás tacones, si necesitas bailar o si quieres mangas, espalda abierta o ajustes concretos.'
        ),
        publicado=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sobremicontenido_peticion_fecha_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('entradilla', models.TextField(blank=True, max_length=300)),
                ('contenido', models.TextField(max_length=4000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrada de blog',
                'verbose_name_plural': 'Entradas de blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.RunPython(crear_entradas_iniciales, migrations.RunPython.noop),
    ]
