# Generated by Django 4.2.30 on 2026-05-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_entradablog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peticion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'solicitud a medida', 'verbose_name_plural': 'solicitudes a medida'},
        ),
        migrations.AlterModelOptions(
            name='sobremicontenido',
            options={'verbose_name': 'contenido de Sobre mí', 'verbose_name_plural': 'contenido de Sobre mí'},
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='contenido',
            field=models.TextField(max_length=4000, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='entradilla',
            field=models.TextField(blank=True, max_length=300, verbose_name='entradilla'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='titulo',
            field=models.CharField(max_length=120, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='asunto',
            field=models.TextField(max_length=60, verbose_name='idea principal'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha del evento'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='peticion',
            field=models.TextField(max_length=500, verbose_name='detalles del diseño'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='presupuesto orientativo'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='talla_aproximada',
            field=models.CharField(blank=True, max_length=30, verbose_name='talla aproximada'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='tipo_prenda',
            field=models.CharField(choices=[('vestido', 'Vestido'), ('traje', 'Traje'), ('camiseta', 'Camiseta'), ('conjunto', 'Conjunto'), ('otro', 'Otro')], default='vestido', max_length=30, verbose_name='tipo de prenda'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peticiones', to=settings.AUTH_USER_MODEL, verbose_name='usuario registrado'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sobre-mi/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL de Instagram'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='texto',
            field=models.TextField(max_length=2500, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='URL de TikTok'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='titulo',
            field=models.CharField(default='¿Quién Soy?', max_length=80, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='sobremicontenido',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='URL de Twitter'),
        ),
    ]
