# Generated by Django 4.1 on 2024-03-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('imagen_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_principal_de', to='diseños.imagen')),
                ('imagenes_adicionales', models.ManyToManyField(related_name='imagenes_adicionales_de', to='diseños.imagen')),
            ],
        ),
    ]
