# Generated by Django 4.1 on 2024-03-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0002_alter_diseño_imagen_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseño',
            old_name='description',
            new_name='descripccion',
        ),
        migrations.RenameField(
            model_name='diseño',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='image',
            new_name='imagen',
        ),
    ]
