# Generated by Django 4.1 on 2024-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0004_alter_diseño_descripccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='imagen_principal',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
