# Generated by Django 4.1 on 2024-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0005_alter_diseño_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
