# Generated by Django 4.2.11 on 2024-05-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0006_alter_diseño_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='diseño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseño_imagenes', to='diseños.diseño'),
        ),
    ]
