# Generated by Django 4.2.11 on 2024-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0007_imagen_diseño'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='fecha_subida',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
