# Generated by Django 4.2.11 on 2024-06-27 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0008_diseño_fecha_subida'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='popularidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
