# Generated by Django 4.2.30 on 2026-05-07 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseños', '0009_diseño_popularidad_alter_diseño_fecha_subida'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='categoria',
            field=models.CharField(choices=[('prenda', 'Prenda'), ('vestido', 'Vestido'), ('traje', 'Traje'), ('camiseta', 'Camiseta'), ('a_medida', 'A medida')], default='prenda', max_length=30),
        ),
        migrations.AddField(
            model_name='diseño',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diseño',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='diseño',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diseño',
            name='talla',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('mensaje', models.TextField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revision'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_compra', to='diseños.diseño')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DisenoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='diseños.diseño')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_disenos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='disenolike',
            constraint=models.UniqueConstraint(fields=('usuario', 'diseño'), name='like_unico_por_usuario_diseno'),
        ),
    ]
