# Generated by Django 4.2.30 on 2026-05-07 17:13

from django.db import migrations, models


def normalizar_estado_pedido(apps, schema_editor):
    Pedido = apps.get_model('diseños', 'Pedido')
    Pedido.objects.filter(estado='pendiente').update(estado='pendiente_pago')


class Migration(migrations.Migration):

    dependencies = [
        ('diseños', '0013_delete_solicitudcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('incidencia', 'Incidencia')], default='pendiente_pago', max_length=20),
        ),
        migrations.RunPython(normalizar_estado_pedido, migrations.RunPython.noop),
    ]
